// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Sergio Marin",
            "url": "https://highercomve.github.io",
            "email": "@highercomve"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calculate": {
            "get": {
                "description": "Calculate mortgage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Calculate mortgage",
                "parameters": [
                    {
                        "description": "Input mortgage calculator",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mortgagemodels.InputP"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mortgage response",
                        "schema": {
                            "$ref": "#/definitions/mortgagemodels.OutputP"
                        }
                    },
                    "400": {
                        "description": "Input is not valid",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Error processing request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "echo.HTTPError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "object"
                }
            }
        },
        "mortgagemodels.InputP": {
            "type": "object",
            "required": [
                "anual_interest",
                "downpayment",
                "period",
                "price",
                "schedule"
            ],
            "properties": {
                "anual_interest": {
                    "type": "number"
                },
                "downpayment": {
                    "type": "number"
                },
                "period": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "schedule": {
                    "type": "string"
                }
            }
        },
        "mortgagemodels.OutputP": {
            "type": "object",
            "properties": {
                "number_of_payments": {
                    "type": "integer"
                },
                "payment": {
                    "type": "number"
                },
                "schedule": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Mortgage Calculator API",
	Description: "Mortgage Calculator API.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
